--任务线配置
TaskLineConfig = {
    [CommonDefine.TASK_LINE_ID_MAIN] = {
        taskIDVar = CommonDefine.VAR_U_ID_TASKLINE1,
        taskStatusVar = CommonDefine.VAR_U_STATUS_TASKLINE1,
        taskCounterVar = CommonDefine.VAR_T_COUNTERDATA_TASKLINE1,
        taskSingleCounterVar = CommonDefine.VAR_U_COUNTER_TASKLINE1,
        firstTaskID = 101,
        taskDataList = { 
          
            [101] = {
                nextid = 102, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='钉耙猫', num=3}},
                targpos = {mapid='em000', x=37, y=41},                
                tasktargparam = 3,
                reward_tab = {{name='经验', num=5000},{name='绑定元宝', num=10000}},
                openbox_num = 10,      --任务完成，直接增加开箱数量
            },
            [102] = {
                nextid = 103, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=700000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            }, 
           [103] = {
                nextid = 104, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='黄沙蚁', num=5}},
                targpos = {mapid='fmg', x=246, y=105},                
                tasktargparam = 5,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=200000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },
           [104] = {
                nextid = 105, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_OPENBOXNUM ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 10,
                reward_tab = {{name='强化石', num=500},{name='经验', num=50000}},
		openbox_num = 20,
            },
           [105] = {
                nextid = 106, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_EQUIPPOS_STRENGTH,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 3,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='经验', num=50000}},
                openbox_num = 0,      --任务完成，直接增加开箱数量
            },
            [106] = {
                nextid = 107, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='白沙蚁', num=8}},
                targpos = {mapid='fmg', x=252, y=93},                
                tasktargparam = 8,
                reward_tab = {{name='绑定元宝', num=50000},{name='金币', num=200000}},
		openbox_num = 20,
            },
            [107] = {
                nextid = 108, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 2,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='经验', num=100000}},
                openbox_num = 0,      --任务完成，直接增加开箱数量
            },
            [108] = {
                nextid = 109, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='钳虫', num=10}},
                targpos = {mapid='xbsd', x=50, y=40},                
                tasktargparam = 10,
                reward_tab = {{name='绑定元宝', num=50000},{name='金币', num=200000}},
		openbox_num = 20,
            },
            [109] = {
                nextid = 110, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='绑定元宝', num=50000},{name='金币', num=700000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
           [110] = {
                nextid = 111, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 120000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=700000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
           [111] = {
                nextid = 112, 
                 acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=300000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
            [112] = {
                nextid = 113, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 3,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=50000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
            [113] = {
                nextid = 114, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='毒蝎', num=15}},
                targpos = {mapid='rxsc800', x=50, y=50}, 
                tasktargparam = 15,
                tasktargdesc = '',
                reward_tab = {{name='书页', num=200},{name='绑定元宝', num=50000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
            [114] = {
                nextid = 115, 
               acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_SKILL_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 3,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=50000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量

            },   
            [115] = {
                nextid = 116, 
               acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 200000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=50000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量

            },   
            [116] = {
                nextid = 117, 
               acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=50000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量

            },   
           [117] = {
                nextid = 118, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 4,
                reward_tab = {{name='强化石', num=200},{name='金币', num=200000}},
		openbox_num = 20,

            },   
            [118] = {
                nextid = 119, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='沃玛守卫', num=15}},
                targpos = {mapid='zlgm', x=50, y=50}, 
                tasktargparam = 15,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量

            },   
           [119] = {
                nextid = 120, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_EQUIPPOS_STRENGTH,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 10,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量

            },   
            [120] = {
                nextid = 121, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 300000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },

            [121] = {
                nextid = 122, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 5,
               tasktargdesc = '',
               reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
               openbox_num = 20,      --任务完成，直接增加开箱数量
             },
            [122] = {
                nextid = 123, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='沃玛守卫', num=15}},
                targpos = {mapid='zlgm', x=50, y=50}, 
                tasktargparam = 15,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },
            [123] = {
                nextid = 124, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [124] = {
                nextid = 125, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 6,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=700000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },             
              [125] = {
                nextid = 126, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='白野猪', num=15}},
                targpos = {mapid='swdt001', x=50, y=50}, 
                tasktargparam = 15,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=700000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },             
              [126] = {
                nextid = 127, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },    
              [127] = {
                nextid = 128, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 750000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [128] = {
                nextid = 129, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 7,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [129] = {
                nextid = 130, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='沃玛守卫', num=20}},
                targpos = {mapid='zzdt001', x=50, y=50}, 
                tasktargparam = 20,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [130] = {
                nextid = 131, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
              [131] = {
                nextid = 132, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 57,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
             [132] = {
                nextid = 133, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_TITLE_UPGRADE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 8,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [133] = {
                nextid = 134, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_KILLMON,
                --一个子任务最多支持三个目标，扩展另开发
                tasktarg_tab = {{monname='沃玛教主', num=15}},
                targpos = {mapid='rxsc016', x=50, y=50}, 
                tasktargparam = 15,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='绑定元宝', num=20000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
              [134] = {
                nextid = 135, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [135] = {
                nextid = 136, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 1000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [136] = {
                nextid = 137, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [137] = {
                nextid = 138, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 65,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
             [138] = {
                nextid = 139, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [139] = {
                nextid = 140, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 70,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
             [140] = {
                nextid = 141, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
            [141] = {
                nextid = 142, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 75,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
            [142] = {
                nextid = 143, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 1800000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },     
             [143] = {
                nextid = 144, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 80,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },   
            [144] = {
                nextid = 145, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [145] = {
                nextid = 146, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 85,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [146] = {
                nextid = 147, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 3500000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [147] = {
                nextid = 148, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
               tasktype = CommonDefine.TASK_TYPE_KILL_SINGLEBOSS ,
                --一个子任务最多支持三个目标，扩展另开发             
                tasktargparam = 1,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=500},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [148] = {
                nextid = 149, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 90,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [149] = {
                nextid = 150, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 6000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [150] = {
                nextid = 151, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 100,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [151] = {
                nextid = 152, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 7800000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [152] = {
                nextid = 153, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 100,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [153] = {
                nextid = 154, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 8500000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [154] = {
                nextid = 155, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 110,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [155] = {
                nextid = 156, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 9000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
            [156] = {
                nextid = 157, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 115,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [157] = {
                nextid = 158, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 9500000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
            [158] = {
                nextid = 159, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 120,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [159] = {
                nextid = 160, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 10000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
            [160] = {
                nextid = 161, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 125,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [161] = {
                nextid = 162, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 11000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [162] = {
                nextid = 163, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 130,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [163] = {
                nextid = 164, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 13000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [164] = {
                nextid = 165, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 135,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [165] = {
                nextid = 166, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 15000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
             [166] = {
                nextid = 167, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 140,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
            [167] = {
                nextid = 168, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 20000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [168] = {
                nextid = 169, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 145,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [169] = {
                nextid = 170, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 25000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
              [170] = {
                nextid = 171, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                tasktype = CommonDefine.TASK_TYPE_LEVEL,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 150,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='绑定元宝', num=2000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
            },  
             [171] = {
                nextid = 0, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '',
                submitdialogue = '',
                 tasktype = CommonDefine.TASK_TYPE_POWERSCORE,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 50000000,
                tasktargdesc = '',
                reward_tab = {{name='强化石', num=200},{name='金币', num=1000000}},
                openbox_num = 20,      --任务完成，直接增加开箱数量
             },  
        }
    },

    [CommonDefine.TASK_LINE_ID_BRANCH] = {
        taskIDVar = CommonDefine.VAR_U_ID_TASKLINE2,
        taskStatusVar = CommonDefine.VAR_U_STATUS_TASKLINE2,
        taskCounterVar = CommonDefine.VAR_T_COUNTERDATA_TASKLINE2,
        taskSingleCounterVar = CommonDefine.VAR_U_COUNTER_TASKLINE2,
        firstTaskID = 501,
        taskDataList = { 
            [501] = {
                nextid = 502, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 1,
                tasktargdesc = '解锁VIP1',
                reward_tab = {{name='绑定元宝', num=1000}},
                openbox_num = 0,
            },
            [502] = {
                nextid = 503, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                 acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 2,
                tasktargdesc = '解锁VIP2',
                reward_tab = {{name='绑定元宝', num=2000}},
            }, 
            [503] = {
                nextid = 504, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 3,
                tasktargdesc = '解锁VIP3',
                reward_tab = {{name='绑定元宝', num=3000}},
            },   
            [504] = {
                nextid = 505, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 4,
                tasktargdesc = '解锁VIP4',
                reward_tab = {{name='绑定元宝', num=4000}},
            },             
           [505] = {
                nextid = 506, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 5,
                tasktargdesc = '解锁VIP5',
                reward_tab = {{name='绑定元宝', num=5000}},
            },             
            [506] = {
                nextid = 507, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 6,
                tasktargdesc = '解锁VIP6',
                reward_tab = {{name='绑定元宝', num=6000}},
            },             
            [507] = {
                nextid = 508, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 7,
                tasktargdesc = '解锁VIP7',
                reward_tab = {{name='绑定元宝', num=7000}},
            },           
            [508] = {
                nextid = 509, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 8,
                tasktargdesc = '解锁VIP8',
                reward_tab = {{name='绑定元宝', num=8000}},
            },           
           [509] = {
                nextid = 510, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 9,
                tasktargdesc = '解锁VIP9',
                reward_tab = {{name='绑定元宝', num=9000}},
            },           
            [510] = {
                nextid = 511, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 10,
                tasktargdesc = '解锁VIP10',
                reward_tab = {{name='绑定元宝', num=10000}},
            },           
            [511] = {
                nextid = 512, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 11,
                tasktargdesc = '解锁VIP11',
                reward_tab = {{name='绑定元宝', num=11000}},
            },           
            [512] = {
                nextid = 513, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 12,
                tasktargdesc = '解锁VIP12',
                reward_tab = {{name='绑定元宝', num=12000}},
            },      
            [513] = {
                nextid = 514, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 13,
                tasktargdesc = '解锁VIP13',
                reward_tab = {{name='绑定元宝', num=13000}},
            },          
           [514] = {
                nextid = 515, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 14,
                tasktargdesc = '解锁VIP14',
                reward_tab = {{name='绑定元宝', num=14000}},
            },          
            [515] = {
                nextid = 0, 
                acceptnpcid = 0,      --'接任务NPC',
                submitnpcid = 0,      --'交任务NPC',
                autoaccept=1, 
                autosubmit=0,
                acceptdialogue = '免费的不一定是廉价的！',
                submitdialogue = '只要有付出就一定会有收获的！',
                tasktype = CommonDefine.TASK_TYPE_FREEVIP,
                --一个子任务最多支持三个目标，扩展另开发
                tasktargparam = 15,
                tasktargdesc = '解锁VIP15',
                reward_tab = {{name='绑定元宝', num=15000}},
            },          

        }
    }    

}

return TaskLineConfig