local config = { 
	[101] = { 
		ID = 101,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀钉耙猫&nbsp;%s/5只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取经验奖励</font></u>",
	},
	[102] = { 
		ID = 102,
		TaskTitle = "<font color='#F7E700'>[主线]  开箱换装</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/10次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[103] = { 
		ID = 103,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/20级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取经验奖励</font></u>",
	},
	[104] = { 
		ID = 104,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>击杀1</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀黄沙蚁&nbsp;%s/5只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[105] = { 
		ID = 105,
		TaskTitle = "<font color='#F7E700'>[主线]  装备强化</font>",
		Haveinfo = "<font colorStyleID='1030'>任意槽位</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>强化到&nbsp;%s/10级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[106] = { 
		ID = 106,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>击杀1</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀白沙蚁&nbsp;%s/10只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取书页奖励</font></u>",
	},
	[107] = { 
		ID = 107,
		TaskTitle = "<font color='#F7E700'>[主线]  技能升级</font>",
		Haveinfo = "<font colorStyleID='1030'>任意技能</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>升级到&nbsp;%s/3级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[108] = { 
		ID = 108,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>击杀1</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀虎斑蚁&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑定元宝奖励</font></u>",
	},
	[109] = { 
		ID = 109,
		TaskTitle = "<font color='#F7E700'>[主线]  宝箱升级</font>",
		Haveinfo = "<font colorStyleID='1030'>宝箱等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取升星石奖励</font></u>",
	},
	[110] = { 
		ID = 110,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/40级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[111] = { 
		ID = 111,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/8万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[112] = { 
		ID = 112,
		TaskTitle = "<font color='#F7E700'>[主线]  开箱换装</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/30次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[113] = { 
		ID = 113,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/50级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[114] = { 
		ID = 114,
		TaskTitle = "<font color='#F7E700'>[主线]  开箱换装</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/40次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[115] = { 
		ID = 115,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/20万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[116] = { 
		ID = 116,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/60级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[117] = { 
		ID = 117,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>击杀1</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀沃玛守卫&nbsp;%s/25只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑定元宝奖励</font></u>",
	},
	[118] = { 
		ID = 118,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/50万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[119] = { 
		ID = 119,
		TaskTitle = "<font color='#F7E700'>[主线]  开箱换装</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/100次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[120] = { 
		ID = 120,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/100级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[121] = { 
		ID = 121,
		TaskTitle = "<font color='#F7E700'>[主线]  提升称号1</font>",
		Haveinfo = "<font colorStyleID='1030'>称号</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;展露头角</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[122] = { 
		ID = 122,
		TaskTitle = "<font color='#F7E700'>[主线]  提升称号2</font>",
		Haveinfo = "<font colorStyleID='1030'>称号</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;江湖少侠</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[123] = { 
		ID = 123,
		TaskTitle = "<font color='#F7E700'>[主线]  提升称号3</font>",
		Haveinfo = "<font colorStyleID='1030'>称号</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;武林豪杰</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[501] = { 
		ID = 501,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP1</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[502] = { 
		ID = 502,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP2</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[503] = { 
		ID = 503,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP3</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/3级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[504] = { 
		ID = 504,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP4</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/4级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[505] = { 
		ID = 505,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP5</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/5级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[506] = { 
		ID = 506,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP6</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/6级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[507] = { 
		ID = 507,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP7</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/7级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[508] = { 
		ID = 508,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP8</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/8级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[509] = { 
		ID = 509,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP9</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/9级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[510] = { 
		ID = 510,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP10</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/10级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[511] = { 
		ID = 511,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP11</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/11级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[512] = { 
		ID = 512,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP12</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/12级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[513] = { 
		ID = 513,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP13</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/13级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[514] = { 
		ID = 514,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP14</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/14级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[515] = { 
		ID = 515,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP15</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/15级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
}
return config
