local config = { 
	[1] = { 
		id = 1,
		monidx = 5002,
		showname = "灰暗尸王",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 40,
		mapid = "publicboss1",
	},
	[2] = { 
		id = 2,
		monidx = 5003,
		showname = "灰暗沃玛教主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 50,
		mapid = "publicboss2",
	},
	[3] = { 
		id = 3,
		monidx = 5004,
		showname = "灰暗祖玛教主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 60,
		mapid = "publicboss3",
	},
	[4] = { 
		id = 4,
		monidx = 5005,
		showname = "灰暗赤月恶魔",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 70,
		mapid = "publicboss4",
	},
	[5] = { 
		id = 5,
		monidx = 5006,
		showname = "灰暗牛魔王",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 75,
		mapid = "publicboss5",
	},
	[6] = { 
		id = 6,
		monidx = 5007,
		showname = "灰暗虹魔教主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 80,
		mapid = "publicboss6",
	},
	[7] = { 
		id = 7,
		monidx = 5008,
		showname = "灰暗黄泉教主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 85,
		mapid = "publicboss7",
	},
	[8] = { 
		id = 8,
		monidx = 5009,
		showname = "灰暗魔龙教主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 90,
		mapid = "publicboss8",
	},
	[9] = { 
		id = 9,
		monidx = 5010,
		showname = "灰暗铅虫君主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 95,
		mapid = "publicboss9",
	},
	[10] = { 
		id = 10,
		monidx = 5011,
		showname = "灰暗蛇蝎君主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 100,
		mapid = "publicboss10",
	},
	[11] = { 
		id = 11,
		monidx = 5012,
		showname = "灰暗火龙神",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 105,
		mapid = "publicboss11",
	},
	[12] = { 
		id = 12,
		monidx = 5013,
		showname = "灰暗血龙将军",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 110,
		mapid = "publicboss12",
	},
	[13] = { 
		id = 13,
		monidx = 5014,
		showname = "灰暗沃玛君主",
		showcolor = 22,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量稀有道具",
		needlevel = 115,
		mapid = "publicboss13",
	},
}
return config
