local config = { 
	[101] = { 
		ID = 101,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/10级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[102] = { 
		ID = 102,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/10次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[103] = { 
		ID = 103,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[104] = { 
		ID = 104,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/20级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[105] = { 
		ID = 105,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/20次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[106] = { 
		ID = 106,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/6万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[107] = { 
		ID = 107,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/30级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[108] = { 
		ID = 108,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/30次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[109] = { 
		ID = 109,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/10万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[110] = { 
		ID = 110,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/40级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[111] = { 
		ID = 111,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/40次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[112] = { 
		ID = 112,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/15万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[113] = { 
		ID = 113,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/50级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[114] = { 
		ID = 114,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/50次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[115] = { 
		ID = 115,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/20万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[116] = { 
		ID = 116,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/60级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[117] = { 
		ID = 117,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/60次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[118] = { 
		ID = 118,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/30万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[119] = { 
		ID = 119,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/70级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[120] = { 
		ID = 120,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/70次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[121] = { 
		ID = 121,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/50万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[122] = { 
		ID = 122,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/80级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[123] = { 
		ID = 123,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/80次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[124] = { 
		ID = 124,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/80万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[125] = { 
		ID = 125,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/85级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[126] = { 
		ID = 126,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/90次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[127] = { 
		ID = 127,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/120万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[128] = { 
		ID = 128,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/90级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[129] = { 
		ID = 129,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/100次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[130] = { 
		ID = 130,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/200万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[131] = { 
		ID = 131,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/95级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[132] = { 
		ID = 132,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/110次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[133] = { 
		ID = 133,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/400万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[134] = { 
		ID = 134,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/100级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[135] = { 
		ID = 135,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/120次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[136] = { 
		ID = 136,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/600万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[137] = { 
		ID = 137,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/105级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[138] = { 
		ID = 138,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/150次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[139] = { 
		ID = 139,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[140] = { 
		ID = 140,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/110级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[141] = { 
		ID = 141,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/170次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[142] = { 
		ID = 142,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1500万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[143] = { 
		ID = 143,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/115级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[144] = { 
		ID = 144,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/190次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[145] = { 
		ID = 145,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[146] = { 
		ID = 146,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/120级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[147] = { 
		ID = 147,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/220次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[148] = { 
		ID = 148,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2500万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[149] = { 
		ID = 149,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/125级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[150] = { 
		ID = 150,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/250次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[151] = { 
		ID = 151,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/3000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[152] = { 
		ID = 152,
		TaskTitle = "<font color='#F7E700'>[主线]  快速升级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/130级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取开箱次数</font></u>",
	},
	[153] = { 
		ID = 153,
		TaskTitle = "<font color='#F7E700'>[主线]  快乐开箱</font>",
		Haveinfo = "<font colorStyleID='1030'>累计</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开箱&nbsp;%s/300次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
	[154] = { 
		ID = 154,
		TaskTitle = "<font color='#F7E700'>[主线]  强的可怕</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/5000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石</font></u>",
	},
}
return config
