local config = { 
	[101] = { 
		ID = 101,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀钉耙猫&nbsp;%s/3只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[102] = { 
		ID = 102,
		TaskTitle = "<font color='#F7E700'>[主线]  初入江湖</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;初入江湖</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[103] = { 
		ID = 103,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀黄沙蚁&nbsp;%s/5只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取经验奖励</font></u>",
	},
	[104] = { 
		ID = 104,
		TaskTitle = "<font color='#F7E700'>[主线]  开箱换装</font>",
		Haveinfo = "<font colorStyleID='1030'>月光宝盒</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>开启&nbsp;%s/10次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[105] = { 
		ID = 105,
		TaskTitle = "<font color='#F7E700'>[主线]  装备强化</font>",
		Haveinfo = "<font colorStyleID='1030'>任意槽位</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>强化到&nbsp;%s/3级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[106] = { 
		ID = 106,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀白沙蚁&nbsp;%s/8只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[107] = { 
		ID = 107,
		TaskTitle = "<font color='#F7E700'>[主线]  展露头角</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;展露头角</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[108] = { 
		ID = 108,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀钳虫&nbsp;%s/10只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑定元宝奖励</font></u>",
	},
	[109] = { 
		ID = 109,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[110] = { 
		ID = 110,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/12万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[111] = { 
		ID = 111,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[112] = { 
		ID = 112,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;江湖少侠</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[113] = { 
		ID = 113,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀毒蝎&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[114] = { 
		ID = 114,
		TaskTitle = "<font color='#F7E700'>[主线]  技不压身</font>",
		Haveinfo = "<font colorStyleID='1030'>技能</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>任意技能升至&nbsp;3级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[115] = { 
		ID = 115,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/18万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[116] = { 
		ID = 116,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[117] = { 
		ID = 117,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;武林豪杰</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[118] = { 
		ID = 118,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀沃玛守卫&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[119] = { 
		ID = 119,
		TaskTitle = "<font color='#F7E700'>[主线]  装备强化</font>",
		Haveinfo = "<font colorStyleID='1030'>任意槽位</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>强化到&nbsp;%s/10级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[120] = { 
		ID = 120,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/30万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[121] = { 
		ID = 121,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;侠骨柔情</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[122] = { 
		ID = 122,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀沃玛守卫&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[123] = { 
		ID = 123,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[124] = { 
		ID = 124,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;名动江湖</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[125] = { 
		ID = 125,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀白野猪&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[126] = { 
		ID = 126,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[127] = { 
		ID = 127,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/75万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[128] = { 
		ID = 128,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;叱诧风云</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[129] = { 
		ID = 129,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀沃玛守卫&nbsp;%s/25只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[130] = { 
		ID = 130,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[131] = { 
		ID = 131,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/57级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[132] = { 
		ID = 132,
		TaskTitle = "<font color='#F7E700'>[主线]  称号提升</font>",
		Haveinfo = "<font colorStyleID='1030'>解锁</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>称号&nbsp;赤胆雄心</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[133] = { 
		ID = 133,
		TaskTitle = "<font color='#F7E700'>[主线]  降妖除魔</font>",
		Haveinfo = "<font colorStyleID='1030'>杀怪</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀沃玛教主&nbsp;%s/15只</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元奖励</font></u>",
	},
	[134] = { 
		ID = 134,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[135] = { 
		ID = 135,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/100万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[136] = { 
		ID = 136,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[137] = { 
		ID = 137,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/65级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[138] = { 
		ID = 138,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[139] = { 
		ID = 139,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/70级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[140] = { 
		ID = 140,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[141] = { 
		ID = 141,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/75级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[142] = { 
		ID = 142,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/180万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[143] = { 
		ID = 143,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/80级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[144] = { 
		ID = 144,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[145] = { 
		ID = 145,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/85级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[146] = { 
		ID = 146,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/350万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[147] = { 
		ID = 147,
		TaskTitle = "<font color='#F7E700'>[主线]  挑战首领</font>",
		Haveinfo = "<font colorStyleID='1030'>个人首领</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>击杀个人首领&nbsp;%s/1次</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[148] = { 
		ID = 148,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/90级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[149] = { 
		ID = 149,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/600万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[150] = { 
		ID = 150,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/100级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[151] = { 
		ID = 151,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/780万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[152] = { 
		ID = 152,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/105级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[153] = { 
		ID = 153,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/850万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[154] = { 
		ID = 154,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/110级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[155] = { 
		ID = 155,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/900万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[156] = { 
		ID = 156,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/115级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[157] = { 
		ID = 157,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/950万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[158] = { 
		ID = 158,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/120级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[159] = { 
		ID = 159,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[160] = { 
		ID = 160,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/125级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[161] = { 
		ID = 161,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1100万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[162] = { 
		ID = 162,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/130级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[163] = { 
		ID = 163,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1300万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[164] = { 
		ID = 164,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/135级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[165] = { 
		ID = 165,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1500万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[166] = { 
		ID = 166,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/140级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[167] = { 
		ID = 167,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[168] = { 
		ID = 168,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/145级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[169] = { 
		ID = 169,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2500万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[170] = { 
		ID = 170,
		TaskTitle = "<font color='#F7E700'>[主线]  提升等级</font>",
		Haveinfo = "<font colorStyleID='1030'>等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>提升至&nbsp;%s/150级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[171] = { 
		ID = 171,
		TaskTitle = "<font color='#F7E700'>[主线]  提升战力</font>",
		Haveinfo = "<font colorStyleID='1030'>战力</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/5000万</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取强化石奖励</font></u>",
	},
	[501] = { 
		ID = 501,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP1</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/1级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[502] = { 
		ID = 502,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP2</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/2级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[503] = { 
		ID = 503,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP3</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/3级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[504] = { 
		ID = 504,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP4</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/4级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[505] = { 
		ID = 505,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP5</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/5级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[506] = { 
		ID = 506,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP6</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/6级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[507] = { 
		ID = 507,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP7</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/7级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[508] = { 
		ID = 508,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP8</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/8级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[509] = { 
		ID = 509,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP9</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/9级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[510] = { 
		ID = 510,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP10</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/10级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[511] = { 
		ID = 511,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP11</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/11级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[512] = { 
		ID = 512,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP12</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/12级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[513] = { 
		ID = 513,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP13</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/13级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[514] = { 
		ID = 514,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP14</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/14级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
	[515] = { 
		ID = 515,
		TaskTitle = "<font color='#F7E700'>[支线]  解锁VIP15</font>",
		Haveinfo = "<font colorStyleID='1030'>VIP等级</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>达到&nbsp;%s/15级</font></u>",
		Completeinfo = "<font colorStyleID='1030'>任务完成</font>&nbsp;&nbsp;<u><font color = '#28ef01' size = '16'>领取绑元</font></u>",
	},
}
return config
