local config = { 
	[1] = { 
		id = 1,
		tasktype = 10,
		tasktargnum = 100,
		taskparam = 0,
		gotoid = 26,
		tasktitle = "开箱换装",
		taskdesc = "累计开箱100次",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":100},{\"name\":\"3级筛子\", \"num\":1}]",
	},
	[2] = { 
		id = 2,
		tasktype = 20,
		tasktargnum = 5,
		taskparam = 0,
		gotoid = 15,
		tasktitle = "个人首领",
		taskdesc = "成功击杀5只个人首领",
		finishrewards = "[{\"name\":\"疗伤药\", \"num\":10},{\"name\":\"升星石\", \"num\":50}]",
	},
	[3] = { 
		id = 3,
		tasktype = 19,
		tasktargnum = 2,
		taskparam = 0,
		gotoid = 16,
		tasktitle = "野外首领",
		taskdesc = "成功击杀2只野外首领",
		finishrewards = "[{\"name\":\"万年雪霜\", \"num\":10},{\"name\":\"绑定元宝\", \"num\":100}]",
	},
	[4] = { 
		id = 4,
		tasktype = 11,
		tasktargnum = 5,
		taskparam = 0,
		gotoid = 3,
		tasktitle = "战力首领",
		taskdesc = "成功击杀5只战力首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"书页\", \"num\":100}]",
	},
	[5] = { 
		id = 5,
		tasktype = 6,
		tasktargnum = 3,
		taskparam = 0,
		gotoid = 4,
		tasktitle = "灵玉首领",
		taskdesc = "成功击杀3只灵玉首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"灵玉精华\", \"num\":50}]",
	},
	[6] = { 
		id = 6,
		tasktype = 22,
		tasktargnum = 2,
		taskparam = 0,
		gotoid = 17,
		tasktitle = "运镖",
		taskdesc = "成功完成2次运镖",
		finishrewards = "[{\"name\":\"大型经验珠\", \"num\":2},{\"name\":\"金币\", \"num\":300000}]",
	},
	[7] = { 
		id = 7,
		tasktype = 23,
		tasktargnum = 3,
		taskparam = 0,
		gotoid = 18,
		tasktitle = "藏宝图",
		taskdesc = "进行3次藏宝图挖宝",
		finishrewards = "[{\"name\":\"金条\", \"num\":1},{\"name\":\"幸运符\", \"num\":1}]",
	},
	[8] = { 
		id = 8,
		tasktype = 1,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 7,
		tasktitle = "槽位强化",
		taskdesc = "进行1次装备槽位强化",
		finishrewards = "[{\"name\":\"强化石\", \"num\":100},{\"name\":\"金币\", \"num\":100000}]",
	},
	[9] = { 
		id = 9,
		tasktype = 2,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 6,
		tasktitle = "槽位升星",
		taskdesc = "进行1次装备槽位升星",
		finishrewards = "[{\"name\":\"升星石\", \"num\":100},{\"name\":\"金币\", \"num\":100000}]",
	},
	[10] = { 
		id = 10,
		tasktype = 5,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 12,
		tasktitle = "灵玉升级",
		taskdesc = "进行1次灵玉槽位强化",
		finishrewards = "[{\"name\":\"灵玉精华\", \"num\":100},{\"name\":\"金币\", \"num\":100000}]",
	},
	[11] = { 
		id = 11,
		tasktype = 7,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 11,
		tasktitle = "魂石合成",
		taskdesc = "进行1次魂石合成",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":100}]",
	},
	[12] = { 
		id = 12,
		tasktype = 8,
		tasktargnum = 3000,
		taskparam = 0,
		gotoid = 19,
		tasktitle = "官职提升",
		taskdesc = "累计获得3000功勋",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":200}]",
	},
	[13] = { 
		id = 13,
		tasktype = 9,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 20,
		tasktitle = "护卫提升",
		taskdesc = "成功进行1次护卫升级",
		finishrewards = "[{\"name\":\"技能秘籍\", \"num\":20},{\"name\":\"金币\", \"num\":100000}]",
	},
}
return config
