local config = { 
	[1] = { 
		id = 1,
		tasktype = 10,
		tasktargnum = 2,
		taskparam = 0,
		gotoid = 5,
		tasktitle = "魔方阵挑战",
		taskdesc = "挑战2次魔方阵",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[2] = { 
		id = 2,
		tasktype = 20,
		tasktargnum = 5,
		taskparam = 0,
		gotoid = 15,
		tasktitle = "个人首领",
		taskdesc = "成功击杀5只个人首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[3] = { 
		id = 3,
		tasktype = 19,
		tasktargnum = 2,
		taskparam = 0,
		gotoid = 16,
		tasktitle = "野外首领",
		taskdesc = "成功击杀2只野外首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[4] = { 
		id = 4,
		tasktype = 11,
		tasktargnum = 5,
		taskparam = 0,
		gotoid = 3,
		tasktitle = "战力首领",
		taskdesc = "成功击杀5只战力首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[5] = { 
		id = 5,
		tasktype = 6,
		tasktargnum = 3,
		taskparam = 0,
		gotoid = 4,
		tasktitle = "灵玉首领",
		taskdesc = "成功击杀3只灵玉首领",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[6] = { 
		id = 6,
		tasktype = 22,
		tasktargnum = 2,
		taskparam = 0,
		gotoid = 17,
		tasktitle = "运镖",
		taskdesc = "成功完成2次运镖",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[7] = { 
		id = 7,
		tasktype = 23,
		tasktargnum = 3,
		taskparam = 0,
		gotoid = 18,
		tasktitle = "藏宝图",
		taskdesc = "进行3次藏宝图挖宝",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[8] = { 
		id = 8,
		tasktype = 1,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 7,
		tasktitle = "槽位强化",
		taskdesc = "进行1次装备槽位强化",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[9] = { 
		id = 9,
		tasktype = 2,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 6,
		tasktitle = "槽位升星",
		taskdesc = "进行1次装备槽位升星",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[10] = { 
		id = 10,
		tasktype = 3,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 9,
		tasktitle = "装备洗炼",
		taskdesc = "进行1次装备洗炼",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[11] = { 
		id = 11,
		tasktype = 5,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 12,
		tasktitle = "灵玉升级",
		taskdesc = "进行1次灵玉槽位强化",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[12] = { 
		id = 12,
		tasktype = 24,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 10,
		tasktitle = "装备合成",
		taskdesc = "进行1次装备合成",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[13] = { 
		id = 13,
		tasktype = 7,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 11,
		tasktitle = "魂石合成",
		taskdesc = "进行1次魂石合成",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[14] = { 
		id = 14,
		tasktype = 8,
		tasktargnum = 3000,
		taskparam = 0,
		gotoid = 19,
		tasktitle = "官职提升",
		taskdesc = "累计获得3000功勋",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
	[15] = { 
		id = 15,
		tasktype = 9,
		tasktargnum = 1,
		taskparam = 0,
		gotoid = 20,
		tasktitle = "护卫提升",
		taskdesc = "成功进行1次护卫升级",
		finishrewards = "[{\"name\":\"绑定元宝\", \"num\":300},{\"name\":\"金币\", \"num\":10000}]",
	},
}
return config
