local config = { 
	[1] = { 
		id = 1,
		monidx = 4011,
		showname = "精英半兽勇士",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 40,
		mapid = "singleboss1",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[2] = { 
		id = 2,
		monidx = 4017,
		showname = "精英山洞蝙蝠",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 50,
		mapid = "singleboss2",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[3] = { 
		id = 3,
		monidx = 4023,
		showname = "精英粪虫",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 60,
		mapid = "singleboss3",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[4] = { 
		id = 4,
		monidx = 4029,
		showname = "精英暗黑战士",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 70,
		mapid = "singleboss4",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[5] = { 
		id = 5,
		monidx = 4039,
		showname = "精英邪恶钳虫",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 75,
		mapid = "singleboss5",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[6] = { 
		id = 6,
		monidx = 4049,
		showname = "精英邪恶毒蛇",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 80,
		mapid = "singleboss6",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[7] = { 
		id = 7,
		monidx = 4054,
		showname = "精英双头血魔",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 85,
		mapid = "singleboss7",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[8] = { 
		id = 8,
		monidx = 4059,
		showname = "精英黑锷蜘蛛",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 90,
		mapid = "singleboss8",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[9] = { 
		id = 9,
		monidx = 4064,
		showname = "精英爆裂蜘蛛",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 95,
		mapid = "singleboss9",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[10] = { 
		id = 10,
		monidx = 4069,
		showname = "精英骷髅战士",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 100,
		mapid = "singleboss10",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[11] = { 
		id = 11,
		monidx = 4074,
		showname = "精英骷髅刀斧手",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 105,
		mapid = "singleboss11",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[12] = { 
		id = 12,
		monidx = 4079,
		showname = "精英牛魔侍卫",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 110,
		mapid = "singleboss12",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[13] = { 
		id = 13,
		monidx = 4080,
		showname = "精英牛魔将军",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 115,
		mapid = "singleboss13",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[14] = { 
		id = 14,
		monidx = 4081,
		showname = "精英牛魔法师",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 120,
		mapid = "singleboss14",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
	[15] = { 
		id = 15,
		monidx = 4082,
		showname = "精英牛魔祭司",
		showcolor = 253,
		tipinfo = "掉落介绍：可获得各职业对应等级角色装备以及大量养成道具",
		needlevel = 125,
		mapid = "singleboss15",
		showrewards = "[{\"name\":\"元宝\", \"num\":1}, {\"name\":\"强化石\", \"num\":1}]",
	},
}
return config
